### ISSUE TITLE
Invariant Violation: requireNativeComponent: "VRTText" was not found in the UIManager

### ISSUE THREAD

**Issue by faizii023** [NativeVision/starter-kit#50] opened 2022-11-05 12:30 UTC
Having this error

**Comment by akhilsanker** [comment] 2023-12-20 09:33
@faizii023 , have you got any workaround?

Facing the same issue here.

**Comment by aboongm** [comment] 2024-02-01 14:09
Has this been solved?

**Comment by robertjcolley** [comment] 2024-02-02 14:50
See #65. Duplicate of issue with Android setup not being "out of the box"

**Closed by robertjcolley** 2024-02-02 14:50 UTC

**Comment by iamalinski** [comment] 2024-02-07 09:36
Facing the same error when following the docs. Any clear way to fix this?
